service: sonnet

provider:
  name: aws
  runtime: python3.6

functions:

  sonnet:
    handler: handler.get_sonnet
    events:
      - http:
          path: sonnet/{id}
          method: get
          cors: true

  shakespeare:
    handler: handler.shakespeare
    events:
      - http:
          path: sonnet/generate
          method: get
          cors: true
